// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package platform

import (
	"time"
)

// GetApp returns the App field.
func (a *Addon) GetApp() *App {
	if a == nil {
		return nil
	}
	return a.App
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (a *Addon) GetID() string {
	if a == nil || a.ID == nil {
		return ""
	}
	return *a.ID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (a *Addon) GetName() string {
	if a == nil || a.Name == nil {
		return ""
	}
	return *a.Name
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (a *App) GetID() string {
	if a == nil || a.ID == nil {
		return ""
	}
	return *a.ID
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (a *App) GetName() string {
	if a == nil || a.Name == nil {
		return ""
	}
	return *a.Name
}

// GetApp returns the App field.
func (a *AppWebhook) GetApp() *App {
	if a == nil {
		return nil
	}
	return a.App
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (a *AppWebhook) GetCreatedAt() time.Time {
	if a == nil || a.CreatedAt == nil {
		return time.Time{}
	}
	return *a.CreatedAt
}

// HasEventTypes checks if AppWebhook has any EventTypes.
func (a *AppWebhook) HasEventTypes() bool {
	if a == nil || a.EventTypes == nil {
		return false
	}
	if len(a.EventTypes) == 0 {
		return false
	}
	return true
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (a *AppWebhook) GetID() string {
	if a == nil || a.ID == nil {
		return ""
	}
	return *a.ID
}

// GetLevel returns the Level field.
func (a *AppWebhook) GetLevel() *WebhookLevel {
	if a == nil {
		return nil
	}
	return a.Level
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (a *AppWebhook) GetName() string {
	if a == nil || a.Name == nil {
		return ""
	}
	return *a.Name
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (a *AppWebhook) GetUpdatedAt() time.Time {
	if a == nil || a.UpdatedAt == nil {
		return time.Time{}
	}
	return *a.UpdatedAt
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (a *AppWebhook) GetURL() string {
	if a == nil || a.URL == nil {
		return ""
	}
	return *a.URL
}

// HasInclude checks if AppWebhookRequest has any Include.
func (a *AppWebhookRequest) HasInclude() bool {
	if a == nil || a.Include == nil {
		return false
	}
	if len(a.Include) == 0 {
		return false
	}
	return true
}

// GetCommand returns the Command field if it's non-nil, zero value otherwise.
func (f *Formation) GetCommand() string {
	if f == nil || f.Command == nil {
		return ""
	}
	return *f.Command
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (f *Formation) GetCreatedAt() time.Time {
	if f == nil || f.CreatedAt == nil {
		return time.Time{}
	}
	return *f.CreatedAt
}

// GetDockerImage returns the DockerImage field.
func (f *Formation) GetDockerImage() *FormationDocker {
	if f == nil {
		return nil
	}
	return f.DockerImage
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (f *Formation) GetID() string {
	if f == nil || f.ID == nil {
		return ""
	}
	return *f.ID
}

// GetSize returns the Size field if it's non-nil, zero value otherwise.
func (f *Formation) GetSize() string {
	if f == nil || f.Size == nil {
		return ""
	}
	return *f.Size
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (f *Formation) GetType() string {
	if f == nil || f.Type == nil {
		return ""
	}
	return *f.Type
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (f *Formation) GetUpdatedAt() time.Time {
	if f == nil || f.UpdatedAt == nil {
		return time.Time{}
	}
	return *f.UpdatedAt
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (f *FormationDocker) GetID() string {
	if f == nil || f.ID == nil {
		return ""
	}
	return *f.ID
}

// HasUpdates checks if FormationDockerBatchUpdateOpts has any Updates.
func (f *FormationDockerBatchUpdateOpts) HasUpdates() bool {
	if f == nil || f.Updates == nil {
		return false
	}
	if len(f.Updates) == 0 {
		return false
	}
	return true
}

// GetDockerImageID returns the DockerImageID field if it's non-nil, zero value otherwise.
func (f *FormationDockerUpdateOpts) GetDockerImageID() string {
	if f == nil || f.DockerImageID == nil {
		return ""
	}
	return *f.DockerImageID
}

// GetAddon returns the Addon field if it's non-nil, zero value otherwise.
func (l *LogDrain) GetAddon() string {
	if l == nil || l.Addon == nil {
		return ""
	}
	return *l.Addon
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (l *LogDrain) GetCreatedAt() time.Time {
	if l == nil || l.CreatedAt == nil {
		return time.Time{}
	}
	return *l.CreatedAt
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (l *LogDrain) GetID() string {
	if l == nil || l.ID == nil {
		return ""
	}
	return *l.ID
}

// GetToken returns the Token field if it's non-nil, zero value otherwise.
func (l *LogDrain) GetToken() string {
	if l == nil || l.Token == nil {
		return ""
	}
	return *l.Token
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (l *LogDrain) GetUpdatedAt() string {
	if l == nil || l.UpdatedAt == nil {
		return ""
	}
	return *l.UpdatedAt
}

// GetURL returns the URL field if it's non-nil, zero value otherwise.
func (l *LogDrain) GetURL() string {
	if l == nil || l.URL == nil {
		return ""
	}
	return *l.URL
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (p *Permission) GetName() string {
	if p == nil || p.Name == nil {
		return ""
	}
	return *p.Name
}

// GetEphemeralApps returns the EphemeralApps field.
func (p *Pipeline) GetEphemeralApps() *PipelineEphemeralAppsConfig {
	if p == nil {
		return nil
	}
	return p.EphemeralApps
}

// GetEnabled returns the Enabled field if it's non-nil, zero value otherwise.
func (p *PipelineEphemeralAppsConfig) GetEnabled() bool {
	if p == nil || p.Enabled == nil {
		return false
	}
	return *p.Enabled
}

// HasPermissions checks if PipelineEphemeralAppsConfig has any Permissions.
func (p *PipelineEphemeralAppsConfig) HasPermissions() bool {
	if p == nil || p.Permissions == nil {
		return false
	}
	if len(p.Permissions) == 0 {
		return false
	}
	return true
}

// GetSynchronization returns the Synchronization field if it's non-nil, zero value otherwise.
func (p *PipelineEphemeralAppsConfig) GetSynchronization() bool {
	if p == nil || p.Synchronization == nil {
		return false
	}
	return *p.Synchronization
}

// HasPermissions checks if PipelineEphemeralAppsConfigUpdateOpts has any Permissions.
func (p *PipelineEphemeralAppsConfigUpdateOpts) HasPermissions() bool {
	if p == nil || p.Permissions == nil {
		return false
	}
	if len(p.Permissions) == 0 {
		return false
	}
	return true
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (p *PipelineMembership) GetCreatedAt() time.Time {
	if p == nil || p.CreatedAt == nil {
		return time.Time{}
	}
	return *p.CreatedAt
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (p *PipelineMembership) GetID() string {
	if p == nil || p.ID == nil {
		return ""
	}
	return *p.ID
}

// HasPermissions checks if PipelineMembership has any Permissions.
func (p *PipelineMembership) HasPermissions() bool {
	if p == nil || p.Permissions == nil {
		return false
	}
	if len(p.Permissions) == 0 {
		return false
	}
	return true
}

// GetPipeline returns the Pipeline field.
func (p *PipelineMembership) GetPipeline() *Pipeline {
	if p == nil {
		return nil
	}
	return p.Pipeline
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (p *PipelineMembership) GetUpdatedAt() time.Time {
	if p == nil || p.UpdatedAt == nil {
		return time.Time{}
	}
	return *p.UpdatedAt
}

// GetUser returns the User field.
func (p *PipelineMembership) GetUser() *User {
	if p == nil {
		return nil
	}
	return p.User
}

// HasPermissions checks if PipelineMembershipRequestOpts has any Permissions.
func (p *PipelineMembershipRequestOpts) HasPermissions() bool {
	if p == nil || p.Permissions == nil {
		return false
	}
	if len(p.Permissions) == 0 {
		return false
	}
	return true
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (u *User) GetEmail() string {
	if u == nil || u.Email == nil {
		return ""
	}
	return *u.Email
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (u *User) GetID() string {
	if u == nil || u.ID == nil {
		return ""
	}
	return *u.ID
}
