// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package postgres

// GetAddon returns the Addon field if it's non-nil, zero value otherwise.
func (m *MTLSEndpoint) GetAddon() string {
	if m == nil || m.Addon == nil {
		return ""
	}
	return *m.Addon
}

// GetApp returns the App field if it's non-nil, zero value otherwise.
func (m *MTLSEndpoint) GetApp() string {
	if m == nil || m.App == nil {
		return ""
	}
	return *m.App
}

// GetCertificateAuthorityChain returns the CertificateAuthorityChain field if it's non-nil, zero value otherwise.
func (m *MTLSEndpoint) GetCertificateAuthorityChain() string {
	if m == nil || m.CertificateAuthorityChain == nil {
		return ""
	}
	return *m.CertificateAuthorityChain
}

// GetEnabledBy returns the EnabledBy field if it's non-nil, zero value otherwise.
func (m *MTLSEndpoint) GetEnabledBy() string {
	if m == nil || m.EnabledBy == nil {
		return ""
	}
	return *m.EnabledBy
}

// GetStatus returns the Status field.
func (m *MTLSEndpoint) GetStatus() *MTLSConfigStatus {
	if m == nil {
		return nil
	}
	return m.Status
}
