// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package connect

import (
	"time"
)

// HasConnections checks if AuthResponse has any Connections.
func (a *AuthResponse) HasConnections() bool {
	if a == nil || a.Connections == nil {
		return false
	}
	if len(a.Connections) == 0 {
		return false
	}
	return true
}

// GetUser returns the User field.
func (a *AuthResponse) GetUser() *ConnectionUser {
	if a == nil {
		return nil
	}
	return a.User
}

// GetAddonType returns the AddonType field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetAddonType() string {
	if a == nil || a.AddonType == nil {
		return ""
	}
	return *a.AddonType
}

// GetAppID returns the AppID field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetAppID() string {
	if a == nil || a.AppID == nil {
		return ""
	}
	return *a.AppID
}

// GetAppName returns the AppName field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetAppName() string {
	if a == nil || a.AppName == nil {
		return ""
	}
	return *a.AppName
}

// GetCell returns the Cell field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetCell() string {
	if a == nil || a.Cell == nil {
		return ""
	}
	return *a.Cell
}

// GetCellLabel returns the CellLabel field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetCellLabel() string {
	if a == nil || a.CellLabel == nil {
		return ""
	}
	return *a.CellLabel
}

// GetDetailURL returns the DetailURL field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetDetailURL() string {
	if a == nil || a.DetailURL == nil {
		return ""
	}
	return *a.DetailURL
}

// GetDisplayName returns the DisplayName field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetDisplayName() string {
	if a == nil || a.DisplayName == nil {
		return ""
	}
	return *a.DisplayName
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetID() string {
	if a == nil || a.ID == nil {
		return ""
	}
	return *a.ID
}

// GetRegion returns the Region field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetRegion() string {
	if a == nil || a.Region == nil {
		return ""
	}
	return *a.Region
}

// GetRegionFlag returns the RegionFlag field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetRegionFlag() string {
	if a == nil || a.RegionFlag == nil {
		return ""
	}
	return *a.RegionFlag
}

// GetRegionLabel returns the RegionLabel field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetRegionLabel() string {
	if a == nil || a.RegionLabel == nil {
		return ""
	}
	return *a.RegionLabel
}

// GetRegionURL returns the RegionURL field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetRegionURL() string {
	if a == nil || a.RegionURL == nil {
		return ""
	}
	return *a.RegionURL
}

// GetResourceName returns the ResourceName field if it's non-nil, zero value otherwise.
func (a *AuthResponseConnection) GetResourceName() string {
	if a == nil || a.ResourceName == nil {
		return ""
	}
	return *a.ResourceName
}

// GetAddonID returns the AddonID field if it's non-nil, zero value otherwise.
func (c *Connection) GetAddonID() string {
	if c == nil || c.AddonID == nil {
		return ""
	}
	return *c.AddonID
}

// GetAppID returns the AppID field if it's non-nil, zero value otherwise.
func (c *Connection) GetAppID() string {
	if c == nil || c.AppID == nil {
		return ""
	}
	return *c.AppID
}

// GetAppName returns the AppName field if it's non-nil, zero value otherwise.
func (c *Connection) GetAppName() string {
	if c == nil || c.AppName == nil {
		return ""
	}
	return *c.AppName
}

// GetBulkPageSize returns the BulkPageSize field if it's non-nil, zero value otherwise.
func (c *Connection) GetBulkPageSize() int {
	if c == nil || c.BulkPageSize == nil {
		return 0
	}
	return *c.BulkPageSize
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (c *Connection) GetCreatedAt() time.Time {
	if c == nil || c.CreatedAt == nil {
		return time.Time{}
	}
	return *c.CreatedAt
}

// GetDatabase returns the Database field.
func (c *Connection) GetDatabase() *ConnectionDatabase {
	if c == nil {
		return nil
	}
	return c.Database
}

// GetDBKey returns the DBKey field if it's non-nil, zero value otherwise.
func (c *Connection) GetDBKey() string {
	if c == nil || c.DBKey == nil {
		return ""
	}
	return *c.DBKey
}

// GetDeletable returns the Deletable field if it's non-nil, zero value otherwise.
func (c *Connection) GetDeletable() bool {
	if c == nil || c.Deletable == nil {
		return false
	}
	return *c.Deletable
}

// GetDetailURL returns the DetailURL field if it's non-nil, zero value otherwise.
func (c *Connection) GetDetailURL() string {
	if c == nil || c.DetailURL == nil {
		return ""
	}
	return *c.DetailURL
}

// GetDogwood returns the Dogwood field if it's non-nil, zero value otherwise.
func (c *Connection) GetDogwood() bool {
	if c == nil || c.Dogwood == nil {
		return false
	}
	return *c.Dogwood
}

// GetFeatures returns the Features field.
func (c *Connection) GetFeatures() *ConnectionFeatures {
	if c == nil {
		return nil
	}
	return c.Features
}

// GetFreeEdition returns the FreeEdition field if it's non-nil, zero value otherwise.
func (c *Connection) GetFreeEdition() bool {
	if c == nil || c.FreeEdition == nil {
		return false
	}
	return *c.FreeEdition
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *Connection) GetID() string {
	if c == nil || c.ID == nil {
		return ""
	}
	return *c.ID
}

// GetInternalName returns the InternalName field if it's non-nil, zero value otherwise.
func (c *Connection) GetInternalName() string {
	if c == nil || c.InternalName == nil {
		return ""
	}
	return *c.InternalName
}

// GetLargeQueryThreshold returns the LargeQueryThreshold field if it's non-nil, zero value otherwise.
func (c *Connection) GetLargeQueryThreshold() int {
	if c == nil || c.LargeQueryThreshold == nil {
		return 0
	}
	return *c.LargeQueryThreshold
}

// GetLogplexLogEnabled returns the LogplexLogEnabled field if it's non-nil, zero value otherwise.
func (c *Connection) GetLogplexLogEnabled() bool {
	if c == nil || c.LogplexLogEnabled == nil {
		return false
	}
	return *c.LogplexLogEnabled
}

// HasMappings checks if Connection has any Mappings.
func (c *Connection) HasMappings() bool {
	if c == nil || c.Mappings == nil {
		return false
	}
	if len(c.Mappings) == 0 {
		return false
	}
	return true
}

// GetMappingsSummaryState returns the MappingsSummaryState field if it's non-nil, zero value otherwise.
func (c *Connection) GetMappingsSummaryState() string {
	if c == nil || c.MappingsSummaryState == nil {
		return ""
	}
	return *c.MappingsSummaryState
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *Connection) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetNotificationUrl returns the NotificationUrl field if it's non-nil, zero value otherwise.
func (c *Connection) GetNotificationUrl() string {
	if c == nil || c.NotificationUrl == nil {
		return ""
	}
	return *c.NotificationUrl
}

// GetOData returns the OData field.
func (c *Connection) GetOData() *ConnectionOData {
	if c == nil {
		return nil
	}
	return c.OData
}

// GetOrganizationID returns the OrganizationID field if it's non-nil, zero value otherwise.
func (c *Connection) GetOrganizationID() string {
	if c == nil || c.OrganizationID == nil {
		return ""
	}
	return *c.OrganizationID
}

// GetPlan returns the Plan field if it's non-nil, zero value otherwise.
func (c *Connection) GetPlan() string {
	if c == nil || c.Plan == nil {
		return ""
	}
	return *c.Plan
}

// GetResourceName returns the ResourceName field if it's non-nil, zero value otherwise.
func (c *Connection) GetResourceName() string {
	if c == nil || c.ResourceName == nil {
		return ""
	}
	return *c.ResourceName
}

// GetSalesforceInfo returns the SalesforceInfo field.
func (c *Connection) GetSalesforceInfo() *ConnectionSalesforceInfo {
	if c == nil {
		return nil
	}
	return c.SalesforceInfo
}

// GetSalesforceInstance returns the SalesforceInstance field if it's non-nil, zero value otherwise.
func (c *Connection) GetSalesforceInstance() string {
	if c == nil || c.SalesforceInstance == nil {
		return ""
	}
	return *c.SalesforceInstance
}

// GetSalesforceRegion returns the SalesforceRegion field if it's non-nil, zero value otherwise.
func (c *Connection) GetSalesforceRegion() string {
	if c == nil || c.SalesforceRegion == nil {
		return ""
	}
	return *c.SalesforceRegion
}

// GetSchemaName returns the SchemaName field if it's non-nil, zero value otherwise.
func (c *Connection) GetSchemaName() string {
	if c == nil || c.SchemaName == nil {
		return ""
	}
	return *c.SchemaName
}

// GetSOAPBatchSize returns the SOAPBatchSize field if it's non-nil, zero value otherwise.
func (c *Connection) GetSOAPBatchSize() int {
	if c == nil || c.SOAPBatchSize == nil {
		return 0
	}
	return *c.SOAPBatchSize
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (c *Connection) GetState() string {
	if c == nil || c.State == nil {
		return ""
	}
	return *c.State
}

// HasTags checks if Connection has any Tags.
func (c *Connection) HasTags() bool {
	if c == nil || c.Tags == nil {
		return false
	}
	if len(c.Tags) == 0 {
		return false
	}
	return true
}

// GetTeamName returns the TeamName field if it's non-nil, zero value otherwise.
func (c *Connection) GetTeamName() string {
	if c == nil || c.TeamName == nil {
		return ""
	}
	return *c.TeamName
}

// GetAccessURL returns the AccessURL field if it's non-nil, zero value otherwise.
func (c *ConnectionCredential) GetAccessURL() string {
	if c == nil || c.AccessURL == nil {
		return ""
	}
	return *c.AccessURL
}

// GetAPIHourlyRateLimit returns the APIHourlyRateLimit field if it's non-nil, zero value otherwise.
func (c *ConnectionCredential) GetAPIHourlyRateLimit() int {
	if c == nil || c.APIHourlyRateLimit == nil {
		return 0
	}
	return *c.APIHourlyRateLimit
}

// GetConnection returns the Connection field.
func (c *ConnectionCredential) GetConnection() *AuthResponseConnection {
	if c == nil {
		return nil
	}
	return c.Connection
}

// GetCredentials returns the Credentials field.
func (c *ConnectionCredential) GetCredentials() *ConnectionCredentialSecrets {
	if c == nil {
		return nil
	}
	return c.Credentials
}

// GetCurrentHourlyAPIUsage returns the CurrentHourlyAPIUsage field if it's non-nil, zero value otherwise.
func (c *ConnectionCredential) GetCurrentHourlyAPIUsage() int {
	if c == nil || c.CurrentHourlyAPIUsage == nil {
		return 0
	}
	return *c.CurrentHourlyAPIUsage
}

// GetEnabled returns the Enabled field if it's non-nil, zero value otherwise.
func (c *ConnectionCredential) GetEnabled() bool {
	if c == nil || c.Enabled == nil {
		return false
	}
	return *c.Enabled
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *ConnectionCredential) GetID() string {
	if c == nil || c.ID == nil {
		return ""
	}
	return *c.ID
}

// HasResources checks if ConnectionCredential has any Resources.
func (c *ConnectionCredential) HasResources() bool {
	if c == nil || c.Resources == nil {
		return false
	}
	if len(c.Resources) == 0 {
		return false
	}
	return true
}

// GetSlug returns the Slug field if it's non-nil, zero value otherwise.
func (c *ConnectionCredential) GetSlug() string {
	if c == nil || c.Slug == nil {
		return ""
	}
	return *c.Slug
}

// GetExported returns the Exported field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialResource) GetExported() bool {
	if c == nil || c.Exported == nil {
		return false
	}
	return *c.Exported
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialResource) GetID() int {
	if c == nil || c.ID == nil {
		return 0
	}
	return *c.ID
}

// GetIsValid returns the IsValid field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialResource) GetIsValid() bool {
	if c == nil || c.IsValid == nil {
		return false
	}
	return *c.IsValid
}

// GetSchemaName returns the SchemaName field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialResource) GetSchemaName() string {
	if c == nil || c.SchemaName == nil {
		return ""
	}
	return *c.SchemaName
}

// GetServices returns the Services field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialResource) GetServices() int {
	if c == nil || c.Services == nil {
		return 0
	}
	return *c.Services
}

// GetTableName returns the TableName field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialResource) GetTableName() string {
	if c == nil || c.TableName == nil {
		return ""
	}
	return *c.TableName
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialResource) GetType() string {
	if c == nil || c.Type == nil {
		return ""
	}
	return *c.Type
}

// GetPassword returns the Password field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialSecrets) GetPassword() string {
	if c == nil || c.Password == nil {
		return ""
	}
	return *c.Password
}

// GetUser returns the User field if it's non-nil, zero value otherwise.
func (c *ConnectionCredentialSecrets) GetUser() string {
	if c == nil || c.User == nil {
		return ""
	}
	return *c.User
}

// GetHost returns the Host field if it's non-nil, zero value otherwise.
func (c *ConnectionDatabase) GetHost() string {
	if c == nil || c.Host == nil {
		return ""
	}
	return *c.Host
}

// GetName returns the Name field if it's non-nil, zero value otherwise.
func (c *ConnectionDatabase) GetName() string {
	if c == nil || c.Name == nil {
		return ""
	}
	return *c.Name
}

// GetPort returns the Port field if it's non-nil, zero value otherwise.
func (c *ConnectionDatabase) GetPort() int {
	if c == nil || c.Port == nil {
		return 0
	}
	return *c.Port
}

// GetDbaExceptionTranslation returns the DbaExceptionTranslation field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetDbaExceptionTranslation() bool {
	if c == nil || c.DbaExceptionTranslation == nil {
		return false
	}
	return *c.DbaExceptionTranslation
}

// GetDbUpdatesForwardInTimeOnly returns the DbUpdatesForwardInTimeOnly field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetDbUpdatesForwardInTimeOnly() bool {
	if c == nil || c.DbUpdatesForwardInTimeOnly == nil {
		return false
	}
	return *c.DbUpdatesForwardInTimeOnly
}

// GetDisableBulkWrites returns the DisableBulkWrites field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetDisableBulkWrites() bool {
	if c == nil || c.DisableBulkWrites == nil {
		return false
	}
	return *c.DisableBulkWrites
}

// GetDriftDetectorBatchDisk returns the DriftDetectorBatchDisk field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetDriftDetectorBatchDisk() bool {
	if c == nil || c.DriftDetectorBatchDisk == nil {
		return false
	}
	return *c.DriftDetectorBatchDisk
}

// GetDriftDetectorStateMachine returns the DriftDetectorStateMachine field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetDriftDetectorStateMachine() bool {
	if c == nil || c.DriftDetectorStateMachine == nil {
		return false
	}
	return *c.DriftDetectorStateMachine
}

// GetEarlySfApiAccess returns the EarlySfApiAccess field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetEarlySfApiAccess() bool {
	if c == nil || c.EarlySfApiAccess == nil {
		return false
	}
	return *c.EarlySfApiAccess
}

// GetForcePicklist255 returns the ForcePicklist255 field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetForcePicklist255() bool {
	if c == nil || c.ForcePicklist255 == nil {
		return false
	}
	return *c.ForcePicklist255
}

// GetMinimalIndexesByDefault returns the MinimalIndexesByDefault field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetMinimalIndexesByDefault() bool {
	if c == nil || c.MinimalIndexesByDefault == nil {
		return false
	}
	return *c.MinimalIndexesByDefault
}

// GetMTLSShieldConnection returns the MTLSShieldConnection field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetMTLSShieldConnection() bool {
	if c == nil || c.MTLSShieldConnection == nil {
		return false
	}
	return *c.MTLSShieldConnection
}

// GetPollDbNoMerge returns the PollDbNoMerge field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetPollDbNoMerge() bool {
	if c == nil || c.PollDbNoMerge == nil {
		return false
	}
	return *c.PollDbNoMerge
}

// GetPollExternalIDs returns the PollExternalIDs field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetPollExternalIDs() bool {
	if c == nil || c.PollExternalIDs == nil {
		return false
	}
	return *c.PollExternalIDs
}

// GetRestCountOnly returns the RestCountOnly field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetRestCountOnly() bool {
	if c == nil || c.RestCountOnly == nil {
		return false
	}
	return *c.RestCountOnly
}

// GetSSHHostKeyVerification returns the SSHHostKeyVerification field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetSSHHostKeyVerification() bool {
	if c == nil || c.SSHHostKeyVerification == nil {
		return false
	}
	return *c.SSHHostKeyVerification
}

// GetSyncRepairImmediately returns the SyncRepairImmediately field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetSyncRepairImmediately() bool {
	if c == nil || c.SyncRepairImmediately == nil {
		return false
	}
	return *c.SyncRepairImmediately
}

// GetTempTablesInTransactions returns the TempTablesInTransactions field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetTempTablesInTransactions() bool {
	if c == nil || c.TempTablesInTransactions == nil {
		return false
	}
	return *c.TempTablesInTransactions
}

// GetTestingFlagOnly returns the TestingFlagOnly field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetTestingFlagOnly() bool {
	if c == nil || c.TestingFlagOnly == nil {
		return false
	}
	return *c.TestingFlagOnly
}

// GetUserAssignmentRules returns the UserAssignmentRules field if it's non-nil, zero value otherwise.
func (c *ConnectionFeatures) GetUserAssignmentRules() bool {
	if c == nil || c.UserAssignmentRules == nil {
		return false
	}
	return *c.UserAssignmentRules
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *ConnectionOData) GetID() int {
	if c == nil || c.ID == nil {
		return 0
	}
	return *c.ID
}

// GetSlug returns the Slug field if it's non-nil, zero value otherwise.
func (c *ConnectionOData) GetSlug() string {
	if c == nil || c.Slug == nil {
		return ""
	}
	return *c.Slug
}

// GetAPIVersion returns the APIVersion field if it's non-nil, zero value otherwise.
func (c *ConnectionSalesforceInfo) GetAPIVersion() string {
	if c == nil || c.APIVersion == nil {
		return ""
	}
	return *c.APIVersion
}

// GetDomain returns the Domain field if it's non-nil, zero value otherwise.
func (c *ConnectionSalesforceInfo) GetDomain() string {
	if c == nil || c.Domain == nil {
		return ""
	}
	return *c.Domain
}

// GetEnvironment returns the Environment field if it's non-nil, zero value otherwise.
func (c *ConnectionSalesforceInfo) GetEnvironment() string {
	if c == nil || c.Environment == nil {
		return ""
	}
	return *c.Environment
}

// GetOrganizationID returns the OrganizationID field if it's non-nil, zero value otherwise.
func (c *ConnectionSalesforceInfo) GetOrganizationID() string {
	if c == nil || c.OrganizationID == nil {
		return ""
	}
	return *c.OrganizationID
}

// GetUsername returns the Username field if it's non-nil, zero value otherwise.
func (c *ConnectionSalesforceInfo) GetUsername() string {
	if c == nil || c.Username == nil {
		return ""
	}
	return *c.Username
}

// GetEmail returns the Email field if it's non-nil, zero value otherwise.
func (c *ConnectionUser) GetEmail() string {
	if c == nil || c.Email == nil {
		return ""
	}
	return *c.Email
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (c *ConnectionUser) GetID() string {
	if c == nil || c.ID == nil {
		return ""
	}
	return *c.ID
}

// GetAccess returns the Access field if it's non-nil, zero value otherwise.
func (m *Mapping) GetAccess() string {
	if m == nil || m.Access == nil {
		return ""
	}
	return *m.Access
}

// GetActivelyWriting returns the ActivelyWriting field if it's non-nil, zero value otherwise.
func (m *Mapping) GetActivelyWriting() bool {
	if m == nil || m.ActivelyWriting == nil {
		return false
	}
	return *m.ActivelyWriting
}

// GetConfig returns the Config field.
func (m *Mapping) GetConfig() *MappingConfig {
	if m == nil {
		return nil
	}
	return m.Config
}

// GetConnection returns the Connection field.
func (m *Mapping) GetConnection() *AuthResponseConnection {
	if m == nil {
		return nil
	}
	return m.Connection
}

// GetCounts returns the Counts field.
func (m *Mapping) GetCounts() *MappingCounts {
	if m == nil {
		return nil
	}
	return m.Counts
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (m *Mapping) GetCreatedAt() time.Time {
	if m == nil || m.CreatedAt == nil {
		return time.Time{}
	}
	return *m.CreatedAt
}

// GetDBCountDate returns the DBCountDate field if it's non-nil, zero value otherwise.
func (m *Mapping) GetDBCountDate() time.Time {
	if m == nil || m.DBCountDate == nil {
		return time.Time{}
	}
	return *m.DBCountDate
}

// GetDetailURL returns the DetailURL field if it's non-nil, zero value otherwise.
func (m *Mapping) GetDetailURL() string {
	if m == nil || m.DetailURL == nil {
		return ""
	}
	return *m.DetailURL
}

// GetErrorsURL returns the ErrorsURL field if it's non-nil, zero value otherwise.
func (m *Mapping) GetErrorsURL() string {
	if m == nil || m.ErrorsURL == nil {
		return ""
	}
	return *m.ErrorsURL
}

// GetHasHCColumns returns the HasHCColumns field if it's non-nil, zero value otherwise.
func (m *Mapping) GetHasHCColumns() bool {
	if m == nil || m.HasHCColumns == nil {
		return false
	}
	return *m.HasHCColumns
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (m *Mapping) GetID() string {
	if m == nil || m.ID == nil {
		return ""
	}
	return *m.ID
}

// GetIsPolling returns the IsPolling field if it's non-nil, zero value otherwise.
func (m *Mapping) GetIsPolling() bool {
	if m == nil || m.IsPolling == nil {
		return false
	}
	return *m.IsPolling
}

// GetObjectName returns the ObjectName field if it's non-nil, zero value otherwise.
func (m *Mapping) GetObjectName() string {
	if m == nil || m.ObjectName == nil {
		return ""
	}
	return *m.ObjectName
}

// GetSalesforceCountDate returns the SalesforceCountDate field if it's non-nil, zero value otherwise.
func (m *Mapping) GetSalesforceCountDate() time.Time {
	if m == nil || m.SalesforceCountDate == nil {
		return time.Time{}
	}
	return *m.SalesforceCountDate
}

// GetSchemaURL returns the SchemaURL field if it's non-nil, zero value otherwise.
func (m *Mapping) GetSchemaURL() string {
	if m == nil || m.SchemaURL == nil {
		return ""
	}
	return *m.SchemaURL
}

// GetSFNotifyEnabled returns the SFNotifyEnabled field if it's non-nil, zero value otherwise.
func (m *Mapping) GetSFNotifyEnabled() bool {
	if m == nil || m.SFNotifyEnabled == nil {
		return false
	}
	return *m.SFNotifyEnabled
}

// GetSFPollingSeconds returns the SFPollingSeconds field if it's non-nil, zero value otherwise.
func (m *Mapping) GetSFPollingSeconds() int {
	if m == nil || m.SFPollingSeconds == nil {
		return 0
	}
	return *m.SFPollingSeconds
}

// GetState returns the State field if it's non-nil, zero value otherwise.
func (m *Mapping) GetState() string {
	if m == nil || m.State == nil {
		return ""
	}
	return *m.State
}

// GetStateDescription returns the StateDescription field if it's non-nil, zero value otherwise.
func (m *Mapping) GetStateDescription() string {
	if m == nil || m.StateDescription == nil {
		return ""
	}
	return *m.StateDescription
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (m *Mapping) GetUpdatedAt() time.Time {
	if m == nil || m.UpdatedAt == nil {
		return time.Time{}
	}
	return *m.UpdatedAt
}

// GetAccess returns the Access field if it's non-nil, zero value otherwise.
func (m *MappingConfig) GetAccess() string {
	if m == nil || m.Access == nil {
		return ""
	}
	return *m.Access
}

// GetAppliedAt returns the AppliedAt field if it's non-nil, zero value otherwise.
func (m *MappingConfig) GetAppliedAt() time.Time {
	if m == nil || m.AppliedAt == nil {
		return time.Time{}
	}
	return *m.AppliedAt
}

// GetRevision returns the Revision field if it's non-nil, zero value otherwise.
func (m *MappingConfig) GetRevision() int {
	if m == nil || m.Revision == nil {
		return 0
	}
	return *m.Revision
}

// GetSFMaxDailyAPICalls returns the SFMaxDailyAPICalls field if it's non-nil, zero value otherwise.
func (m *MappingConfig) GetSFMaxDailyAPICalls() int {
	if m == nil || m.SFMaxDailyAPICalls == nil {
		return 0
	}
	return *m.SFMaxDailyAPICalls
}

// GetSFNotifyEnabled returns the SFNotifyEnabled field if it's non-nil, zero value otherwise.
func (m *MappingConfig) GetSFNotifyEnabled() bool {
	if m == nil || m.SFNotifyEnabled == nil {
		return false
	}
	return *m.SFNotifyEnabled
}

// GetSFPollingSeconds returns the SFPollingSeconds field if it's non-nil, zero value otherwise.
func (m *MappingConfig) GetSFPollingSeconds() int {
	if m == nil || m.SFPollingSeconds == nil {
		return 0
	}
	return *m.SFPollingSeconds
}

// GetCount returns the Count field if it's non-nil, zero value otherwise.
func (m *MappingCounts) GetCount() int {
	if m == nil || m.Count == nil {
		return 0
	}
	return *m.Count
}

// GetErrors returns the Errors field if it's non-nil, zero value otherwise.
func (m *MappingCounts) GetErrors() int {
	if m == nil || m.Errors == nil {
		return 0
	}
	return *m.Errors
}

// GetPending returns the Pending field if it's non-nil, zero value otherwise.
func (m *MappingCounts) GetPending() int {
	if m == nil || m.Pending == nil {
		return 0
	}
	return *m.Pending
}

// GetSF returns the SF field if it's non-nil, zero value otherwise.
func (m *MappingCounts) GetSF() int {
	if m == nil || m.SF == nil {
		return 0
	}
	return *m.SF
}

// GetConnection returns the Connection field.
func (m *MappingsExport) GetConnection() *Connection {
	if m == nil {
		return nil
	}
	return m.Connection
}

// HasMappings checks if MappingsExport has any Mappings.
func (m *MappingsExport) HasMappings() bool {
	if m == nil || m.Mappings == nil {
		return false
	}
	if len(m.Mappings) == 0 {
		return false
	}
	return true
}

// GetVersion returns the Version field if it's non-nil, zero value otherwise.
func (m *MappingsExport) GetVersion() int {
	if m == nil || m.Version == nil {
		return 0
	}
	return *m.Version
}
