// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package redis

// GetMaxmemoryPolicy returns the MaxmemoryPolicy field.
func (c *Config) GetMaxmemoryPolicy() *ConfigMaxmemory {
	if c == nil {
		return nil
	}
	return c.MaxmemoryPolicy
}

// GetNotifyKeyspaceEvents returns the NotifyKeyspaceEvents field.
func (c *Config) GetNotifyKeyspaceEvents() *ConfigNotifyKeyspaceEvents {
	if c == nil {
		return nil
	}
	return c.NotifyKeyspaceEvents
}

// GetStandbySegvWorkaround returns the StandbySegvWorkaround field.
func (c *Config) GetStandbySegvWorkaround() *ConfigStandbySegvWorkaround {
	if c == nil {
		return nil
	}
	return c.StandbySegvWorkaround
}

// GetTimeout returns the Timeout field.
func (c *Config) GetTimeout() *ConfigTimeout {
	if c == nil {
		return nil
	}
	return c.Timeout
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (c *ConfigMaxmemory) GetDefault() string {
	if c == nil || c.Default == nil {
		return ""
	}
	return *c.Default
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *ConfigMaxmemory) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (c *ConfigMaxmemory) GetValue() string {
	if c == nil || c.Value == nil {
		return ""
	}
	return *c.Value
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (c *ConfigNotifyKeyspaceEvents) GetDefault() string {
	if c == nil || c.Default == nil {
		return ""
	}
	return *c.Default
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *ConfigNotifyKeyspaceEvents) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (c *ConfigNotifyKeyspaceEvents) GetValue() string {
	if c == nil || c.Value == nil {
		return ""
	}
	return *c.Value
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (c *ConfigStandbySegvWorkaround) GetDefault() bool {
	if c == nil || c.Default == nil {
		return false
	}
	return *c.Default
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *ConfigStandbySegvWorkaround) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (c *ConfigStandbySegvWorkaround) GetValue() bool {
	if c == nil || c.Value == nil {
		return false
	}
	return *c.Value
}

// GetDefault returns the Default field if it's non-nil, zero value otherwise.
func (c *ConfigTimeout) GetDefault() int {
	if c == nil || c.Default == nil {
		return 0
	}
	return *c.Default
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (c *ConfigTimeout) GetDescription() string {
	if c == nil || c.Description == nil {
		return ""
	}
	return *c.Description
}

// GetValue returns the Value field if it's non-nil, zero value otherwise.
func (c *ConfigTimeout) GetValue() int {
	if c == nil || c.Value == nil {
		return 0
	}
	return *c.Value
}

// GetNotifyKeyspaceEvents returns the NotifyKeyspaceEvents field if it's non-nil, zero value otherwise.
func (c *ConfigUpdateRequest) GetNotifyKeyspaceEvents() string {
	if c == nil || c.NotifyKeyspaceEvents == nil {
		return ""
	}
	return *c.NotifyKeyspaceEvents
}

// GetTimeout returns the Timeout field if it's non-nil, zero value otherwise.
func (c *ConfigUpdateRequest) GetTimeout() int {
	if c == nil || c.Timeout == nil {
		return 0
	}
	return *c.Timeout
}
