// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package data

// GetAddonName returns the AddonName field if it's non-nil, zero value otherwise.
func (p *Privatelink) GetAddonName() string {
	if p == nil || p.AddonName == nil {
		return ""
	}
	return *p.AddonName
}

// GetAddonUUID returns the AddonUUID field if it's non-nil, zero value otherwise.
func (p *Privatelink) GetAddonUUID() string {
	if p == nil || p.AddonUUID == nil {
		return ""
	}
	return *p.AddonUUID
}

// HasAllowedAccounts checks if Privatelink has any AllowedAccounts.
func (p *Privatelink) HasAllowedAccounts() bool {
	if p == nil || p.AllowedAccounts == nil {
		return false
	}
	if len(p.AllowedAccounts) == 0 {
		return false
	}
	return true
}

// GetAppName returns the AppName field if it's non-nil, zero value otherwise.
func (p *Privatelink) GetAppName() string {
	if p == nil || p.AppName == nil {
		return ""
	}
	return *p.AppName
}

// HasConnections checks if Privatelink has any Connections.
func (p *Privatelink) HasConnections() bool {
	if p == nil || p.Connections == nil {
		return false
	}
	if len(p.Connections) == 0 {
		return false
	}
	return true
}

// GetServiceName returns the ServiceName field if it's non-nil, zero value otherwise.
func (p *Privatelink) GetServiceName() string {
	if p == nil || p.ServiceName == nil {
		return ""
	}
	return *p.ServiceName
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (p *Privatelink) GetStatus() string {
	if p == nil || p.Status == nil {
		return ""
	}
	return *p.Status
}

// GetARN returns the ARN field if it's non-nil, zero value otherwise.
func (p *PrivatelinkAllowedAccounts) GetARN() string {
	if p == nil || p.ARN == nil {
		return ""
	}
	return *p.ARN
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (p *PrivatelinkAllowedAccounts) GetStatus() string {
	if p == nil || p.Status == nil {
		return ""
	}
	return *p.Status
}

// GetEndpointID returns the EndpointID field if it's non-nil, zero value otherwise.
func (p *PrivatelinkConnections) GetEndpointID() string {
	if p == nil || p.EndpointID == nil {
		return ""
	}
	return *p.EndpointID
}

// GetHostname returns the Hostname field if it's non-nil, zero value otherwise.
func (p *PrivatelinkConnections) GetHostname() string {
	if p == nil || p.Hostname == nil {
		return ""
	}
	return *p.Hostname
}

// GetOwnerARN returns the OwnerARN field if it's non-nil, zero value otherwise.
func (p *PrivatelinkConnections) GetOwnerARN() string {
	if p == nil || p.OwnerARN == nil {
		return ""
	}
	return *p.OwnerARN
}

// GetStatus returns the Status field if it's non-nil, zero value otherwise.
func (p *PrivatelinkConnections) GetStatus() string {
	if p == nil || p.Status == nil {
		return ""
	}
	return *p.Status
}
