// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package general

import (
	"time"
)

// GetCIDR returns the CIDR field if it's non-nil, zero value otherwise.
func (m *MtlsIPRule) GetCIDR() string {
	if m == nil || m.CIDR == nil {
		return ""
	}
	return *m.CIDR
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (m *MtlsIPRule) GetCreatedAt() time.Time {
	if m == nil || m.CreatedAt == nil {
		return time.Time{}
	}
	return *m.CreatedAt
}

// GetDescription returns the Description field if it's non-nil, zero value otherwise.
func (m *MtlsIPRule) GetDescription() string {
	if m == nil || m.Description == nil {
		return ""
	}
	return *m.Description
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (m *MtlsIPRule) GetID() string {
	if m == nil || m.ID == nil {
		return ""
	}
	return *m.ID
}

// GetStatus returns the Status field.
func (m *MtlsIPRule) GetStatus() *MTLSIPRuleStatus {
	if m == nil {
		return nil
	}
	return m.Status
}

// GetUpdatedAt returns the UpdatedAt field if it's non-nil, zero value otherwise.
func (m *MtlsIPRule) GetUpdatedAt() time.Time {
	if m == nil || m.UpdatedAt == nil {
		return time.Time{}
	}
	return *m.UpdatedAt
}
