// Copyright 2020
//
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.
// Code generated by gen-accessors; DO NOT EDIT.
package scheduler

import (
	"time"
)

// GetAttributes returns the Attributes field.
func (j *Job) GetAttributes() *JobAttributes {
	if j == nil {
		return nil
	}
	return j.Attributes
}

// GetID returns the ID field if it's non-nil, zero value otherwise.
func (j *Job) GetID() string {
	if j == nil || j.ID == nil {
		return ""
	}
	return *j.ID
}

// GetType returns the Type field if it's non-nil, zero value otherwise.
func (j *Job) GetType() string {
	if j == nil || j.Type == nil {
		return ""
	}
	return *j.Type
}

// GetAt returns the At field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetAt() int {
	if j == nil || j.At == nil {
		return 0
	}
	return *j.At
}

// GetCommand returns the Command field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetCommand() string {
	if j == nil || j.Command == nil {
		return ""
	}
	return *j.Command
}

// GetCreatedAt returns the CreatedAt field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetCreatedAt() time.Time {
	if j == nil || j.CreatedAt == nil {
		return time.Time{}
	}
	return *j.CreatedAt
}

// GetDynoSize returns the DynoSize field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetDynoSize() string {
	if j == nil || j.DynoSize == nil {
		return ""
	}
	return *j.DynoSize
}

// GetEvery returns the Every field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetEvery() int {
	if j == nil || j.Every == nil {
		return 0
	}
	return *j.Every
}

// GetExpireAfter returns the ExpireAfter field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetExpireAfter() time.Time {
	if j == nil || j.ExpireAfter == nil {
		return time.Time{}
	}
	return *j.ExpireAfter
}

// GetPause returns the Pause field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetPause() time.Time {
	if j == nil || j.Pause == nil {
		return time.Time{}
	}
	return *j.Pause
}

// GetRanAt returns the RanAt field if it's non-nil, zero value otherwise.
func (j *JobAttributes) GetRanAt() time.Time {
	if j == nil || j.RanAt == nil {
		return time.Time{}
	}
	return *j.RanAt
}

// GetAttributes returns the Attributes field.
func (j *JobDataRequest) GetAttributes() *JobAttributeRequest {
	if j == nil {
		return nil
	}
	return j.Attributes
}

// GetData returns the Data field.
func (j *JobModifyResponse) GetData() *Job {
	if j == nil {
		return nil
	}
	return j.Data
}

// GetData returns the Data field.
func (j *JobRequestNew) GetData() *JobDataRequest {
	if j == nil {
		return nil
	}
	return j.Data
}

// HasData checks if Jobs has any Data.
func (j *Jobs) HasData() bool {
	if j == nil || j.Data == nil {
		return false
	}
	if len(j.Data) == 0 {
		return false
	}
	return true
}
